
CREATE TABLE  IF NOT EXISTS `sales_forecasting` (
	`ds` TIMESTAMP,
	`yhat` FLOAT,
);

CREATE TABLE  IF NOT EXISTS `sales` (
	`status` TEXT,
	`city` TEXT,
	`country_iso2` TEXT,
	`date_created` TIMESTAMP,
	`email` TEXT,
	`method` TEXT,
	`name` TEXT,
	`postcode` TEXT,
	`product_id` TEXT,
	`qty_ordered` FLOAT,
	`qty_shipped` FLOAT,
	`quote_item_id` TEXT,
	`region` TEXT,
	`region_code` TEXT,
	`region_id` TEXT,
	`sku` TEXT,
	`base_currency_code` TEXT,
	`shipping_description` TEXT,
	`updated_at` TEXT,
	`increment_id` TEXT,
	`grand_total` FLOAT,
	`quote_id` TEXT,
	`order_id` TEXT,
	`customer_id` TEXT,
	`total` FLOAT,
	`firstname` TEXT,
	`lastname` TEXT,
	`Year` FLOAT,
	`Month` FLOAT,
	`Week` FLOAT,
	`Day` FLOAT,
	`Dayofweek` FLOAT,
	`Dayofyear` FLOAT,
	`just_date` TEXT,
	`year_month` TEXT,
	`month_abbr` TEXT,
	`day_abbr` TEXT,
	`hour` FLOAT,
	`quater` FLOAT,
	`session` TEXT,
	`cc_code` TEXT,
);

CREATE TABLE  IF NOT EXISTS `sales_summary` (
	`status` TEXT,
	`city` TEXT,
	`country_iso2` TEXT,
	`date_created` TIMESTAMP,
	`email` TEXT,
	`method` TEXT,
	`name` TEXT,
	`postcode` TEXT,
	`product_id` TEXT,
	`qty_ordered` FLOAT,
	`qty_shipped` FLOAT,
	`quote_item_id` TEXT,
	`region` TEXT,
	`region_code` TEXT,
	`region_id` TEXT,
	`sku` TEXT,
	`base_currency_code` TEXT,
	`shipping_description` TEXT,
	`updated_at` TEXT,
	`increment_id` TEXT,
	`grand_total` FLOAT,
	`quote_id` TEXT,
	`order_id` TEXT,
	`customer_id` TEXT,
	`total_sales` FLOAT,
	`firstname` TEXT,
	`lastname` TEXT,
	`Year` FLOAT,
	`Month` FLOAT,
	`Week` FLOAT,
	`Day` FLOAT,
	`Dayofweek` FLOAT,
	`Dayofyear` FLOAT,
	`just_date` TEXT,
	`year_month` TEXT,
	`month_abbr` TEXT,
	`day_abbr` TEXT,
	`hour` FLOAT,
	`quater` FLOAT,
	`session` TEXT,
	`cc_code` TEXT,
	`created_at` TEXT,
	`year` INT,
	`interval` INT,
	`min` TEXT,
	`max` TEXT,
	`len` INT,
	`mean` FLOAT,
	`std_` FLOAT,
	`avg_diff` FLOAT,
	`win_back` TEXT,
	`new_customer` INT,
	`min_c` TEXT,
	`max_c` TEXT,
	`diff` TEXT,
	`avg_day` FLOAT,
	`avg_metric` FLOAT,
	`recent_order` INT,
	`churn_label` TEXT,
	`freq_pur` TEXT,
	`repeat_customer` INT,
);

CREATE TABLE  IF NOT EXISTS `customer_signup` (
	`year_month` TEXT,
	`counts` INT,
);

CREATE TABLE  IF NOT EXISTS `rfm` (
	`email` TEXT,
	`recency` INT,
	`frequency` INT,
	`monetary` FLOAT,
	`frequency_log` FLOAT,
	`monetary_log` FLOAT,
	`recency_log` FLOAT,
	`Cluster` INT,
	`R` INT,
	`F` INT,
	`M` INT,
	`RFM` TEXT,
	`S_RFM` INT,
	`RFM_int` INT,
	`cust_segment` TEXT,
	`quad_segment` TEXT,
	`f_label` TEXT,
	`avg_order_value` FLOAT,
	`firstname` TEXT,
	`lastname` TEXT,
	`min_c` TEXT,
	`max_c` TEXT,
);

CREATE TABLE  IF NOT EXISTS `rfm_one` (
	`email` TEXT,
	`recency` INT,
	`frequency` INT,
	`monetary` FLOAT,
	`frequency_log` FLOAT,
	`monetary_log` FLOAT,
	`recency_log` FLOAT,
	`Cluster` INT,
	`R` INT,
	`F` INT,
	`M` INT,
	`RFM` TEXT,
	`S_RFM` INT,
	`RFM_int` INT,
	`cust_segment` TEXT,
	`quad_segment` TEXT,
	`f_label` TEXT,
	`avg_order_value` FLOAT,
	`firstname` TEXT,
	`lastname` TEXT,
	`min_c` TEXT,
	`max_c` TEXT,
);

CREATE TABLE  IF NOT EXISTS `churn_forecasting` (
	`ds` TIMESTAMP,
	`trend` FLOAT,
	`yhat_lower` FLOAT,
	`yhat_upper` FLOAT,
	`trend_lower` FLOAT,
	`trend_upper` FLOAT,
	`additive_terms` FLOAT,
	`additive_terms_lower` FLOAT,
	`additive_terms_upper` FLOAT,
	`weekly` FLOAT,
	`weekly_lower` FLOAT,
	`weekly_upper` FLOAT,
	`yearly` FLOAT,
	`yearly_lower` FLOAT,
	`yearly_upper` FLOAT,
	`multiplicative_terms` FLOAT,
	`multiplicative_terms_lower` FLOAT,
	`multiplicative_terms_upper` FLOAT,
	`yhat` FLOAT,
);

CREATE TABLE  IF NOT EXISTS `cohort_half` (
	`NewCustomer` FLOAT,
	`30Days` FLOAT,
	`60Days` FLOAT,
	`90Days` FLOAT,
	`120Days` FLOAT,
	`150Days` FLOAT,
	`180Days` FLOAT,
);

CREATE TABLE  IF NOT EXISTS `cohort_year` (
	`NewCustomer` FLOAT,
	`30Days` FLOAT,
	`60Days` FLOAT,
	`90Days` FLOAT,
	`120Days` FLOAT,
	`150Days` FLOAT,
	`180Days` FLOAT,
	`210Days` FLOAT,
	`240Days` FLOAT,
	`270Days` FLOAT,
	`300Days` FLOAT,
	`330Days` FLOAT,
	`360Days` FLOAT,
);

CREATE TABLE  IF NOT EXISTS `retention_half` (
	`NewCustomer` FLOAT,
	`30Days` FLOAT,
	`60Days` FLOAT,
	`90Days` FLOAT,
	`120Days` FLOAT,
	`150Days` FLOAT,
	`180Days` FLOAT,
);

CREATE TABLE  IF NOT EXISTS `retention_year` (
	`NewCustomer` FLOAT,
	`30Days` FLOAT,
	`60Days` FLOAT,
	`90Days` FLOAT,
	`120Days` FLOAT,
	`150Days` FLOAT,
	`180Days` FLOAT,
	`210Days` FLOAT,
	`240Days` FLOAT,
	`270Days` FLOAT,
	`300Days` FLOAT,
	`330Days` FLOAT,
	`360Days` FLOAT,
);

CREATE TABLE  IF NOT EXISTS `products` (
	`status` TEXT,
	`product_id` TEXT,
	`qty_ordered` FLOAT,
	`sku` TEXT,
	`total_sales` FLOAT,
	`just_date` TEXT,
	`id` TEXT,
	`product_name` TEXT,
	`price` FLOAT,
	`item_id` TEXT,
	`stock_id` TEXT,
	`product_stock_qty` FLOAT,
	`product_update_date` TEXT,
	`low_stock_date` TEXT,
	`backorders` TEXT,
);

CREATE TABLE  IF NOT EXISTS `product_table` (
	`just_date` TEXT,
	`product_name` TEXT,
	`product_update_date` TEXT,
	`year_month` TEXT,
	`year` TEXT,
	`product_stock_qty` FLOAT,
	`qty_ordered` FLOAT,
);

CREATE TABLE  IF NOT EXISTS `custom_options` (
	`created_at` TEXT,
	`order_id` TEXT,
	`name` TEXT,
	`option_id` TEXT,
	`option_id_name` TEXT,
	`option_value` TEXT,
	`option_value_name` TEXT,
	`qty_ordered` FLOAT,
);

CREATE TABLE  IF NOT EXISTS `stock` (
	`item_id` TEXT,
	`product_id` TEXT,
	`stock_id` TEXT,
	`qty` TEXT,
	`is_in_stock` TEXT,
	`is_qty_decimal` TEXT,
	`show_default_notification_message` TEXT,
	`use_config_min_qty` TEXT,
	`min_qty` TEXT,
	`use_config_min_sale_qty` TEXT,
	`min_sale_qty` TEXT,
	`use_config_max_sale_qty` TEXT,
	`max_sale_qty` TEXT,
	`use_config_backorders` TEXT,
	`backorders` TEXT,
	`use_config_notify_stock_qty` TEXT,
	`notify_stock_qty` TEXT,
	`use_config_qty_increments` TEXT,
	`qty_increments` TEXT,
	`use_config_enable_qty_inc` TEXT,
	`enable_qty_increments` TEXT,
	`use_config_manage_stock` TEXT,
	`manage_stock` TEXT,
	`low_stock_date` TEXT,
	`is_decimal_divided` TEXT,
	`stock_status_changed_auto` TEXT,
	`sku` TEXT,
	`created_at` TEXT,
	`updated_at` TEXT,
);

CREATE TABLE  IF NOT EXISTS `payments` (
	`order_id` TEXT,
	`sku` TEXT,
	`name` TEXT,
	`original_price` FLOAT,
	`price` FLOAT,
	`qty_ordered` FLOAT,
	`customer_email` TEXT,
	`created_at` TEXT,
	`updated_at` TEXT,
	`status` TEXT,
	`base_currency_code` TEXT,
	`discount_amount` FLOAT,
	`store_id` FLOAT,
	`amount_ordered` FLOAT,
	`amount_paid` FLOAT,
	`amount_refunded` FLOAT,
	`method` TEXT,
	`city` TEXT,
	`country_id` TEXT,
	`region` TEXT,
	`base_price_total` FLOAT,
	`price_total` FLOAT,
	`transaction_type` TEXT,
	`price_total_tt` FLOAT,
);

CREATE TABLE  IF NOT EXISTS `raw_order_items` (
	`amount_refunded` FLOAT,
	`base_amount_refunded` FLOAT,
	`base_discount_amount` FLOAT,
	`base_discount_invoiced` FLOAT,
	`base_discount_tax_compensation_invoiced` FLOAT,
	`base_original_price` FLOAT,
	`base_price` FLOAT,
	`base_price_incl_tax` FLOAT,
	`base_row_invoiced` FLOAT,
	`base_row_total` FLOAT,
	`base_row_total_incl_tax` FLOAT,
	`base_tax_amount` FLOAT,
	`base_tax_invoiced` FLOAT,
	`base_weee_tax_applied_amount` FLOAT,
	`base_weee_tax_applied_row_amnt` FLOAT,
	`base_weee_tax_disposition` FLOAT,
	`base_weee_tax_row_disposition` FLOAT,
	`created_at` TEXT,
	`discount_amount` FLOAT,
	`discount_invoiced` FLOAT,
	`discount_percent` FLOAT,
	`free_shipping` FLOAT,
	`discount_tax_compensation_invoiced` FLOAT,
	`is_qty_decimal` FLOAT,
	`is_virtual` FLOAT,
	`item_id` FLOAT,
	`name` TEXT,
	`no_discount` FLOAT,
	`order_id` FLOAT,
	`original_price` FLOAT,
	`price` FLOAT,
	`price_incl_tax` FLOAT,
	`product_id` FLOAT,
	`product_type` TEXT,
	`qty_canceled` FLOAT,
	`qty_invoiced` FLOAT,
	`qty_ordered` FLOAT,
	`qty_refunded` FLOAT,
	`qty_shipped` FLOAT,
	`quote_item_id` FLOAT,
	`row_invoiced` FLOAT,
	`row_total` FLOAT,
	`row_total_incl_tax` FLOAT,
	`row_weight` FLOAT,
	`sku` TEXT,
	`store_id` FLOAT,
	`tax_amount` FLOAT,
	`tax_invoiced` FLOAT,
	`tax_percent` FLOAT,
	`updated_at` TEXT,
	`weee_tax_applied` TEXT,
	`weee_tax_applied_amount` FLOAT,
	`weee_tax_applied_row_amount` FLOAT,
	`weee_tax_disposition` FLOAT,
	`weee_tax_row_disposition` FLOAT,
	`weight` FLOAT,
	`product_option` TEXT,
	`extension_attributes` TEXT,
	`customer_email` TEXT,
	`qty_backordered` FLOAT,
	`base_discount_tax_compensation_amount` FLOAT,
	`discount_tax_compensation_amount` FLOAT,
	`discount_tax_compensation_canceled` FLOAT,
	`tax_canceled` FLOAT,
);